type = "card"
title = "Honors & Awards"

[[items]]
title = "ICML 2026 Gold Reviewer"
date = "2026"

[[items]]
title = "Outstanding Paper Award"
subtitle = "EMNLP"
date = "2025"
content = "7 selected out of 8,174 submissions."

[[items]]
title = "Outstanding Graduate of Beijing"
subtitle = "Beijing Municipal Education Commission"
date = "2024"

[[items]]
title = "Benjamin Miller Memorial Fellowship"
subtitle = "Columbia University"
date = "2023"

[[items]]
title = "National Scholarship for Graduates"
subtitle = "Ministry of Education of China"
date = "2022"

[[items]]
title = "Outstanding Graduate of Shanghai"
subtitle = "Shanghai Municipal Education Commission"
date = "2021"

[[items]]
title = "National Scholarship for Undergraduates"
subtitle = "Ministry of Education of China"
date = "2018, 2019, 2020"
