[site]
title = "Yifan Sun"
description = "CS Ph.D. student at UIUC."
favicon = "/favicon.svg"
last_updated = "September 2026"

[author]
name = "Yifan Sun"
title = "CS PhD Student"
institution = "University of Illinois at Urbana-Champaign"
avatar = "/images/profile/primary.jpg"
alternate_avatar = "/images/profile/alternate.jpg"

[social]
email = "yifan50@illinois.edu"
google_scholar = "https://scholar.google.com/citations?user=S3Fwr_wAAAAJ&hl=en"

[features]
enable_likes = false
enable_one_page_mode = false

[i18n]
enabled = false
locales = ["en"]
default_locale = "en"
mode = "fixed"
fixed_locale = "en"
persist = false
switcher = false

[i18n.labels]
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
