type = "card"
title = "Industry Experience"

[[items]]
title = "Research Scientist Intern"
subtitle = "FAIR, Meta"
date = "May 2026 – Aug 2026"
content = "Conducted research on LLM pre-training."

[[items]]
title = "Applied Scientist Intern"
subtitle = "AGI Foundations, Amazon"
date = "May 2025 – Aug 2025"
content = "Conducted research on LLM post-training."
