type = "publication"
title = "Preprints and Publications"
description = "† indicates these authors contributed equally to this work. See my Google Scholar for earlier publications."
google_scholar_url = "https://scholar.google.com/citations?user=S3Fwr_wAAAAJ&hl=en"
source = "publications.bib"
